In [17]:
import pandas as pd
import numpy as np
from parse_excel import Parser

In [18]:
parser = Parser()

In [19]:
DATA_DIR = "data/"
data = parser.read_all_data(DATA_DIR+"Database_matrix_modified.xlsx")
X_game = parser.get_game_features(data)
X_code = parser.get_code_features(data)

In [20]:
NUM_STUDS = 42
#X_code = X_code[:NUM_STUDS]

In [5]:
#data_code = data[:NUM_STUDS,6:8]

In [6]:
#data_code.shape

(42, 2)

In [21]:
grades = parser.parse_grades(data,42)

In [40]:
#grades

In [23]:
dist = parser.distribute_grades(grades)

In [24]:
dist

array([1, 1, 1, 2, 0, 0, 2, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0])

In [25]:
#TEST_SET = list(range(36,42))
#TEST_SET.append(23)

In [34]:
#TRAIN_SET = list(set(range(42)) - set(TEST_SET))
perm = np.random.permutation(42)
X_code = X_code[perm]
dist = dist[perm]

In [35]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()

In [36]:
X_train = X_code[:35]
y_train = dist[:35]
X_test = X_code[35:]
y_test = dist[35:]

In [37]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [38]:
clf.predict(X_test)

array([1, 0, 0, 2, 1, 1, 2])

In [39]:
y_test

array([1, 0, 0, 1, 1, 1, 1])

In [31]:
clf.get_params

<bound method BaseEstimator.get_params of DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')>

In [34]:
clf.predict_proba(X_test)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [8]:
## Research

In [10]:
X_train = X_code[:NUM_STUDS]
X_test = X_code[NUM_STUDS:]

In [13]:
y_train = dist

In [15]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [16]:
clf.predict(X_test)

array([1, 2, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0])

In [17]:
X_test.shape

(12, 10)

In [6]:
cgs = parser.parse_cgpa(data,NUM_STUDS)
cgs

array([ 7.  ,  8.03,  8.7 ,  7.08, 10.  ,  9.  ,  6.83,  9.67,  9.57,
        9.01,  7.63,  9.07,  7.55,  9.39,  6.74,  7.9 ,  8.89,  9.16,
        8.53,  9.61,  8.78,  8.61,  7.88,  6.8 ,  9.61,  8.04,  9.45,
        7.64,  9.47,  9.29,  9.62,  9.48,  9.24,  9.32,  7.37,  5.  ,
        9.96,  7.2 ,  6.4 ,  8.62,  8.82,  8.82,  9.3 ,  9.51,  8.36,
        7.4 ,  8.58,  8.51,  8.13,  8.29,  6.9 ,  9.03,  6.  ,  6.61])

In [7]:
dist_cg = parser.distribute_cgs(cgs)
dist_cg

array([2, 1, 1, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 2, 1, 0, 1, 0, 1, 1,
       2, 2, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 2, 1, 1, 1, 0, 0,
       1, 2, 1, 1, 1, 1, 2, 0, 2, 2])

In [10]:
perm = np.random.permutation(54)

In [12]:
X_code = X_code[perm]
dist_cg = dist_cg[perm]

In [13]:
X_train = X_code[:45]
X_test = X_code[45:]
y_train = dist_cg[:45]
y_test = dist_cg[45:]

In [14]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [15]:
clf.predict(X_test)

array([1, 0, 2, 2, 2, 2, 1, 0, 1])

In [16]:
y_test

array([1, 1, 1, 0, 0, 1, 0, 1, 0])